version: "3.8"
services:
    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
        networks:
            - app-network

    server:
        image: dbidaux/proyectohorizon27_server:latest
        env_file:
            - /home/debian/env_files/server.env
        ports:
            - "8080:8080"
        depends_on:
            - mongo
        networks:
            - app-network

    client:
        image: dbidaux/proyectohorizon27_client:latest
        ports:
            - "3000:3000"
        depends_on:
            - server
        networks:
            - app-network

volumes:
    mongo-data:

networks:
    app-network:
        driver: bridge
