version: "3"

services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "15000:15000"
        restart: always

    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        env_file:
            - ./server/.env
        depends_on:
            - mongo
        restart: always

    mongo:
        image: arm64v8/mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db

volumes:
    mongo-data:
